baseurl: ''
domain: realestate.zp.ua
url: 'https://www.realestate.zp.ua'
addre: 'https://add.realestate.zp.ua'

encoding: UTF-8
lang: uk_UA
language: Українська
timezone: Europe/Helsinki
country: Україна
region: Запорізька область
region_slug: zaporizhzhska
region_size: .89rem

usd: 37.60
eur: 41.50
nbu: 36.5686

title: Мережа Вебсайтів Нерухомості
keywords: будинки, квартири, земля, житло, нежитлові приміщення, кімнати, оренда, частини квартири, частини будинку, гаражі, місця паркування, ділянки
description: Купівля, продаж і тривала та подобова оренда квартир, будинків, землі, комерційної нежитлової нерухомості в Запоріжжі та області
name: Регіональна нерухомість
brand: Нерухомість
logo: '/assets/images/logo.svg'

author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Мережа Вебсайтів Нерухомості в&nbsp;Україні
  address: 76018, м. Івано-Франківськ, вул.&nbsp;Січових&nbsp;Стрільців,&nbsp;56
  phone_main: 380974949649
  phone_hot: 380974949649
  phone_fax: 380974949649
  phone_sms: 380504949649
  phone_advert: 380504949649
  phone_buy_sell: 380974949649
  phone_add_ads: 380504949649
  phone_submit_ads: 380504949649
  phone_support: 380504949649
  phone_buy: 380974949649
  phone_sell: 380974949649
  email: info@realestate.zp.ua
  www: https://www.realestate.zp.ua/

markdown: kramdown
kramdown:
  auto_ids: false

collections:
  help:
    output: true
  stabs:
    output: true
  otabs:
    output: true
  owners:
    output: true

defaults:
  - scope:
      path: /*/data/*.json
    values:
      layout: "null"
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: /articles/
      type: "articles"
    values:
      layout: "articles"
  - scope:
      path: /news/
      type: "news"
    values:
      layout: "news"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
  style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

main_url: https://www.realestate.net.ua
